version: '3.8'

services:
  # --- BROKER MQTT (Le Transporteur) ---
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: iot_mosquitto
    restart: always
    ports:
      # - "1883:1883" # Port Standard - DESACTIVE (utiliser 8883 TLS)
      # - "9001:9001" # Port Websocket - DESACTIVE (utiliser 8883 TLS)
      - "8883:8883" # Secure MQTT - SEUL PORT ACTIF
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  # --- LOGIQUE & AUTOMATISATION (Le Cerveau) ---
  node-red:
    image: nodered/node-red:latest
    container_name: iot_nodered
    restart: always
    environment:
      - TZ=Europe/Paris
      - NODE_OPTIONS=--dns-result-order=ipv4first
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data
      - ./mosquitto/config/certs:/data/certs:ro
    depends_on:
      - mosquitto
